### ISSUE TITLE
Renaming WBI variables

### ISSUE THREAD

**Issue by naveenoid** [robotology/wholebodyinterface#1]
The variables such as joint angles, rototranslation  and the corresponding derivatives etc. need to be renamed to the standard used in http://wiki.icub.org/codyco/dox/html/dynamics_notation.html to avoid confusions. 

For instance q should be renamed across all functions in the interface as q_j since it obviously refers to joint angles.

**Comment by traversaro** [comment]
As wholebodyinterface is deprecated, we will not solve this issue.
